// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var iframe;

  iframe = document.getElementById('iframe');

  $.pkg.init(iframe.contentWindow);

  $.pkg.listen('/select/file', function() {
    ({
      extensions: ['jpg', 'jpeg', 'gif', 'png']
    });
    return chrome.fileSystem.chooseEntry({
      type: 'openFile',
      accepts: [
        {
          extensions: extensions
        }
      ]
    }, function(entry) {
      return entry.file(function(file) {
        var reader;
        reader = new FileReader();
        reader.onloadend = function() {
          return $.pkg.send('/file/selected', [this.result]);
        };
        return reader.readAsDataURL(file);
      });
    });
  });

}).call(this);
